apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-go-app
  labels:
    app: assessment-go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assessment-go-app
  template:
    metadata:
      labels:
        app: assessment-go-app
    spec:
      containers:
      - name: assesengineer442/asment-go-app
        image: assessment-go-app:latest
        ports:
        - containerPort: 8080 
        livenessProbe:
          httpGet:
            path: /        
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: / 
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-go-app
  labels:
    app: assessment-go-app
spec:
  type: LoadBalancer
  selector:
    app: assessment-go-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
